export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export type INCREMENT_COUNTER = typeof INCREMENT_COUNTER;

export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export type DECREMENT_COUNTER = typeof DECREMENT_COUNTER;

export const RESET_COUNTER = 'RESET_COUNTER';
export type RESET_COUNTER = typeof RESET_COUNTER;
