export const COUNTER_INCREMENT = "COUNTER_INCREMENT";
export type COUNTER_INCREMENT = typeof COUNTER_INCREMENT;

export const COUNTER_DECREMENT = "COUNTER_DECREMENT";
export type COUNTER_DECREMENT = typeof COUNTER_DECREMENT;

export const COUNTER_ADD = "COUNTER_ADD";
export type COUNTER_ADD = typeof COUNTER_ADD;

export const COUNTER_RESET = "COUNTER_RESET";
export type COUNTER_RESET = typeof COUNTER_RESET;
