export const manifestServiceUrl = 'https://1u31fuekv5.execute-api.eu-west-1.amazonaws.com/prod/manifest/';

export const MICAPI_MANIFEST_REQUEST = 'MICAPI_MANIFEST_REQUEST';
export type MICAPI_MANIFEST_REQUEST = typeof MICAPI_MANIFEST_REQUEST;
export const MICAPI_MANIFEST_RESPONSE = 'MICAPI_MANIFEST_RESPONSE';
export type MICAPI_MANIFEST_RESPONSE = typeof MICAPI_MANIFEST_RESPONSE;
export const MICAPI_MANIFEST_FAILURE = 'MICAPI_MANIFEST_FAILURE';
export type MICAPI_MANIFEST_FAILURE = typeof MICAPI_MANIFEST_FAILURE;

export const MICAPI_METADATA_MANIFEST_REQUEST = 'MICAPI_METADATA_MANIFEST_REQUEST';
export type MICAPI_METADATA_MANIFEST_REQUEST = typeof MICAPI_METADATA_MANIFEST_REQUEST;
export const MICAPI_METADATA_MANIFEST_RESPONSE = 'MICAPI_METADATA_MANIFEST_RESPONSE';
export type MICAPI_METADATA_MANIFEST_RESPONSE = typeof MICAPI_METADATA_MANIFEST_RESPONSE;
export const MICAPI_METADATA_MANIFEST_FAILURE = 'MICAPI_METADATA_MANIFEST_FAILURE';
export type MICAPI_METADATA_MANIFEST_FAILURE = typeof MICAPI_METADATA_MANIFEST_FAILURE;

export const MICAPI_AUTH_LOGIN_REQUEST = 'MICAPI_AUTH_LOGIN_REQUEST';
export type MICAPI_AUTH_LOGIN_REQUEST = typeof MICAPI_AUTH_LOGIN_REQUEST;
export const MICAPI_AUTH_LOGIN_RESPONSE = 'MICAPI_AUTH_LOGIN_RESPONSE';
export type MICAPI_AUTH_LOGIN_RESPONSE = typeof MICAPI_AUTH_LOGIN_RESPONSE;
export const MICAPI_AUTH_LOGIN_SUCCESS = 'MICAPI_AUTH_LOGIN_SUCCESS';
export type MICAPI_AUTH_LOGIN_SUCCESS = typeof MICAPI_AUTH_LOGIN_SUCCESS;
export const MICAPI_AUTH_LOGIN_FAILURE = 'MICAPI_AUTH_LOGIN_FAILURE';
export type MICAPI_AUTH_LOGIN_FAILURE = typeof MICAPI_AUTH_LOGIN_FAILURE;
