export const HOSTNAME_ONCHANGE_EVENT = 'HOSTNAME_ONCHANGE_EVENT';
export type HOSTNAME_ONCHANGE_EVENT = typeof HOSTNAME_ONCHANGE_EVENT;
export const HOSTNAME_ONBLUR_EVENT = 'HOSTNAME_ONBLUR_EVENT';
export type HOSTNAME_ONBLUR_EVENT = typeof HOSTNAME_ONBLUR_EVENT;

export const FETCH_MIC_MANIFEST = 'FETCH_MIC_MANIFEST';
export type FETCH_MIC_MANIFEST = typeof FETCH_MIC_MANIFEST;
export const RECEIVE_MIC_MANIFEST = 'RECEIVE_MIC_MANIFEST';
export type RECEIVE_MIC_MANIFEST = typeof RECEIVE_MIC_MANIFEST;

export const FETCH_API_MANIFEST = 'FETCH_API_MANIFEST';
export type FETCH_API_MANIFEST = typeof FETCH_API_MANIFEST;
export const RECEIVE_API_MANIFEST = 'RECEIVE_API_MANIFEST';
export type RECEIVE_API_MANIFEST = typeof RECEIVE_API_MANIFEST;

export const HOSTNAME_CHANGE_SUCCEEDED = 'HOSTNAME_CHANGE_SUCCEEDED';
export type HOSTNAME_CHANGE_SUCCEEDED = typeof HOSTNAME_CHANGE_SUCCEEDED;

export const HOSTNAME_CHANGE_FAILED = 'HOSTNAME_CHANGE_FAILED';
export type HOSTNAME_CHANGE_FAILED = typeof HOSTNAME_CHANGE_FAILED;

export type MicHostinfoAnyActionType = (
  HOSTNAME_ONCHANGE_EVENT |
  HOSTNAME_ONBLUR_EVENT |
  FETCH_MIC_MANIFEST |
  RECEIVE_MIC_MANIFEST |
  FETCH_API_MANIFEST |
  RECEIVE_API_MANIFEST |
  HOSTNAME_CHANGE_SUCCEEDED |
  HOSTNAME_CHANGE_FAILED
);
