export const MICSTACK_CONNECT_START = 'MICSTACK_CONNECT_START';
export type MICSTACK_CONNECT_START = typeof MICSTACK_CONNECT_START;
export const MICSTACK_CONNECT_SUCCESS = 'MICSTACK_CONNECT_SUCCESS';
export type MICSTACK_CONNECT_SUCCESS = typeof MICSTACK_CONNECT_SUCCESS;
export const MICSTACK_CONNECT_FAILURE = 'MICSTACK_CONNECT_FAILURE';
export type MICSTACK_CONNECT_FAILURE = typeof MICSTACK_CONNECT_FAILURE;
